### ISSUE TITLE
Browsing the container only gives directory listing

### ISSUE THREAD

**Issue by larsfagerbakke** [furritos/docker-btdex#11]
Hello,

Followed your install guide and got the container up and running. As the tutorial states I should now be able to browse the container on http port 5800 in my browser (Chrome), but I get a directory listing.

Did I miss something?

**Comment by larsfagerbakke** [comment]
A simple fix is to update the tutorial to `... favorite web browse and open http://localhost:5800/vnc.html` instead of `... favorite web browse and open http://localhost:5800`.

**Comment by furritos** [comment]
Fair enough point, I'll update the tutorial.

**Comment by furritos** [comment]
Documentation updated.
