### ISSUE TITLE
Cant fit window

### ISSUE THREAD

**Issue by larsfagerbakke** [furritos/docker-btdex#12]
After navigating to the container and clicked "MINING" tab for instance, I cant see the full width. I've tried to increase the width. It helps a bit, but even at 1920 is still not wide enough.

![image](https://user-images.githubusercontent.com/3427549/204091139-a8c2fb67-d496-41b0-b8e6-91b3c4372fe2.png)

**Comment by furritos** [comment]
Are you saying you want wider options?  Or are you asking about that black block on the right side?

**Comment by furritos** [comment]
Closing issue as no comments have come in for over 2 months.
