### ISSUE TITLE
Where is your VOLUME in the Dockerfile?

### ISSUE THREAD

**Issue by paulpoco** [furritos/docker-btdex#4]
Where is your VOLUME in the Dockerfile?

VOLUME /config /data

**Comment by furritos** [comment]
Didn't specifically add it in.  The common use case is covered in the documentation vis-à-vis the quick start section.  If an end-user wants to implement it in the manner that is documented, they can choose to do so.

However, if also affords the more experience user the option to put in advanced configurations (such as NFS-backed volumes).  I try to keep the Dockerfile as thin as possible.

**Comment by furritos** [comment]
Closing issue as README.md covers this topic.
