### ISSUE TITLE
Made an UnRAID template

### ISSUE THREAD

**Issue by paulpoco** [furritos/docker-btdex#5]
Made an Unraid Template.

It works but I had to change port 5900 to 5901 as at least on my system 5900 was already in use probably my VM.

https://github.com/paulpoco/docker-templates/blob/master/paulpoco/btdex.xml

It is a start, you are welcome to refine it.  Myself I wouldn't use it for mining so the plots and cache are not needed by me.

There are some display issues.
![image](https://user-images.githubusercontent.com/801414/156100974-362ca81c-f551-440f-932a-a1aa38ddf93b.png)

**Comment by furritos** [comment]
Thanks for this!  Yeah, let me take a look and go from there.

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/156101918-e03f7201-5811-4227-8641-f60b27c2eb9c.png)

**Comment by paulpoco** [comment]
Those display issues are gone, weird.  I removed and added container again a few times to get the icon right.

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/156102289-341d05d4-eb98-43c7-999f-b7fda13303ec.png)
Clicking the thing that would open a browser tab of course doesn't go anywhere.

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/156103090-488e6c47-14fb-4428-ab2b-1bbacc4206f9.png)
I had to add the 2nd line to template repository section of Unraid.  I don't see it in the app tab like I see signum-node

**Comment by paulpoco** [comment]
@furritos what does port 5900 do?   I had to change that to 5901 in the Template as 5900 caused a conflict with something else in Unraid.   Of course the Dockerfile on your Github is what is used to to build the Docker and put it on DockerHub,

I guess I could set in Template the Host port to 5901 and the container port to 5900.
![image](https://user-images.githubusercontent.com/801414/156104487-0a3b031b-1313-483a-9d19-2b6a2d9e9475.png)

**Comment by furritos** [comment]
> ![image](https://user-images.githubusercontent.com/801414/156102289-341d05d4-eb98-43c7-999f-b7fda13303ec.png) Clicking the thing that would open a browser tab of course doesn't go anywhere.

This is a known issue and is being tracked as issue #2.

**Comment by furritos** [comment]
> @furritos what does port 5900 do? I had to change that to 5901 in the Template as 5900 caused a conflict with something else in Unraid. Of course the Dockerfile on your Github is what is used to to build the Docker and put it on DockerHub,
> 
> I guess I could set in Template the Host port to 5901 and the container port to 5900. ![image](https://user-images.githubusercontent.com/801414/156104487-0a3b031b-1313-483a-9d19-2b6a2d9e9475.png)

Please review [the ports section](https://github.com/furritos/docker-btdex#ports) in this repository.  Port 5900 in the container is the optional port if you want to use the VNC desktop client.  It can be mapped to any external port.  UnRAID gives you visibility through its Docker allocation dropdown.  I would leave it the default value of 5900 and let the UnRAID system administrator manage that.  Again, it's an optional port and the main port that we should mandate is 5800.

**Comment by furritos** [comment]
Closing as UnRAID template is now published.
